### ISSUE TITLE
API returns all ItemObjects from a single item meta data

### ISSUE THREAD

**Issue by PixelGuy123** [benjaminpants/MTM101BMDE#3]
Grappling hooks contains all of their variants (1, 2, 3, 4 and 5 uses). But if you use a function such as .GetAllWithFlags(). It'll not return a single grappling hook (5), but 5 of them.
Duplicates:
![image](https://github.com/benjaminpants/MTM101BMDE/assets/89644121/a4155ea6-62b0-46ad-93dc-f6950632c2d3)
Code:
![image](https://github.com/benjaminpants/MTM101BMDE/assets/89644121/0715277c-8bf4-4383-969b-946925c97d58)

**Comment by PixelGuy123** [comment]
Update: Figured out the bug for you
![image](https://github.com/benjaminpants/MTM101BMDE/assets/89644121/a37052af-358e-409b-8bad-efc2485db73e)
The grappling hook "variants" are added to the meta storage, but all of these instances are pointing out to the **same** ItemMetaData, resulting in the same grappling hook **value**.

**Comment by benjaminpants** [comment]
What you described is not the solution, them pointing to the same metadata is intentional. I already know the actual problem so I'll be implementing the fix.

**Comment by benjaminpants** [comment]
(Hopefully) fixed in commit 8b3facc
